### ISSUE TITLE
📌We are migrating to Material UI

### ISSUE THREAD

**Issue by imabp** [Tech-Phantoms/Tech_Phantoms_website#164]
#  📌We will be  migrating to Material UI 
Slowly slowly every component will be converted to Material UI ones. 

Anyone who would like to take part in this process, please comment down on this issue.

I think we should break this process as much as possible, due to the sheer number of components currently present. 

## TODO
- #### Landing Page
- [x] Appbar
- [x] Drawer - @Souvikns 
- [x] Footer - @senshiii
- [x] landing page layout - @imabp 
- #### Project Page
- [x] Project card - @Souvikns 
- [x] Project page layout - @Souvikns 
- #### Team Page
- [ ] Team Profile Card - @sandy9808 
- [ ] Team Page layout
- #### Event Page - @Souvikns 
- [x] Event card 
- [ ] Event Layout 
- #### 404 Page
- [x] 404 page layout - @sandy9808 

---
> Comment to pick components.
---

**Comment by Samridhi-98** [comment]
I would like to contribute in this.

**Comment by adithyaakrishna** [comment]
@imabp I would like to contribute to this :)
I've experience in MUI too, if that counts 🚀

**Comment by senshiii** [comment]
I would like to contribute.

**Comment by Souvikns** [comment]
I am working on the drawer component

**Comment by senshiii** [comment]
@Souvikns Can you assign me the Footer?

**Comment by imabp** [comment]
@adithyaakrishna @Samridhi-98 we have updated the isssue description, you can take a look and choose one of them. So that all contributors can evenly participate.

Make sure, you send PR to `development` branch. 
Also do read, Readme, in order to setup dummy Airtable API environments

**Comment by Souvikns** [comment]
## Drawer design 
Will convert to dark automatically when converting to dark theme. 
![image](https://user-images.githubusercontent.com/41781438/94998408-345fe100-05cf-11eb-95b5-fc005d431fcc.png)

**Comment by imabp** [comment]
@Souvikns can we use `background-color: tomato` for the drawer. And font color set to white.

**Comment by imabp** [comment]
Great work @Souvikns . Drawer is migrated to materia ui

**Comment by Souvikns** [comment]
I am also taking the project card.

**Comment by sandy9808** [comment]
@Souvikns is on 🔥

**Comment by senshiii** [comment]
Raised a PR for the footer. Here is a quick comparison of the existing Footer (Top) and the Migrated One. The PR contains only the Migrated Version. Previous version files are removed.

![Mobile View](https://user-images.githubusercontent.com/67961536/95000600-f3bc9380-05df-11eb-9b88-aea922bb06b7.png)
![Desktop View](https://user-images.githubusercontent.com/67961536/95000601-f5865700-05df-11eb-85ee-b499509eb55b.png)

**Comment by imabp** [comment]
@senshiii which theme are you using for chrome ?
Looks amazing.

**Comment by senshiii** [comment]
@imabp I am using this theme [When the Night Falls](https://chrome.google.com/webstore/detail/when-the-night-falls-100/lpmmeefjafijboofpccfngkpckkjpadm?hl=en)

**Comment by sandy9808** [comment]
@imabp I will take care of the 404 page because that also depends on chakra ui, i will convert it to material ui..

**Comment by Souvikns** [comment]
Let me fix the project layout that might fix this the holder issue.

**Comment by imabp** [comment]
@Samridhi-98 @adithyaakrishna you can convert any of the followings 
- #### Team Page
- [ ] Team Profile Card
- [ ] Team Page layout
- #### Event Page 
- [ ] Event card 
- [ ] Event Layout

**Comment by Souvikns** [comment]
Today till 4 pm if no one claims the Events page then I will start with it.

**Comment by imabp** [comment]
Working on landing Page

**Comment by larbikhounti** [comment]
**I'm interested**

**Comment by imabp** [comment]
@larbikhounti on which page, you are interested ? Please comment

**Comment by larbikhounti** [comment]
> @larbikhounti on which page, you are interested ? Please comment
Team Profile Card

**Comment by imabp** [comment]
Please read project read me @larbikhounti

**Comment by sandy9808** [comment]
Can I take the **Team profile card**, it seems tough to me to do so, but I will try.

**Comment by imabp** [comment]
Go Ahead @sandy9808 . One must try new things.

**Comment by sandy9808** [comment]
@iambp the svg icons for social handles used should be replaced by material ui icons or not ?

**Comment by imabp** [comment]
@sandy9808  Material UI Icons. 
But we should have to use the color property. 
Like for linkedin, it should be of blue color types. 

Also, are you using Paper for making the team card picture part, if not, I suggest Paper from Material UI.
Point to note is that, we are fetching data from airtable, so that should not break ?😊

**Comment by sandy9808** [comment]
ok i will use material ui icons then. And now that you have updated me i will use Paper component for the image. 👍

**Comment by sandy9808** [comment]
What will be the size of the profile image, will it be same for all ?

**Comment by imabp** [comment]
yes @sanday

**Comment by sandy9808** [comment]
And the size will be?
