### ISSUE TITLE
Integrate API and remove airtable.

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Tech_Phantoms_website#225]
## TODO
- [ ] Remove airtable logic 
- [x] fetch data from the API
- [ ] Update the hooks with new data format.
