### ISSUE TITLE
Events Page new design

### ISSUE THREAD

**Issue by Souvikns** [Tech-Phantoms/Tech_Phantoms_website#246]
# Design
![103171778-de6ca380-4874-11eb-9f43-2dc206bd966d](https://user-images.githubusercontent.com/41781438/103172752-b3398280-487b-11eb-8bda-bbb7c651d6a6.png)

---
# Introduction 
So we are having three sections that we need to build, First is the heading, which for now is just an `h1` tag, a filter section that will contain logic to change the view below, and lastly the events themselves. Currently, we are fetching data from our airtable instance, though in the future we will replace it with our server, our data fetching layer will still give the same format of data. I would like to talk about how we can tackle this issue, or what I think we should do. 
 
## Events Page
In `/src/pages/events/index.jsx` there is no logic for fetching the data. Actually, we are fetching the data in the individual section namely `/section/events.jsx/, but with the new design we do need to access the data in two different components, and so I think it will be better to fetch the data in top component and pass it to the sub-components. I think all the state-related logic should be in this component. 

## Filter Section 
In this section, we will have the UI for the user to interact with. Basically, this is where the user can choose one of the two options namely `upcoming` and `previous`,. So in this component, we do not need to access any data but rather functions to modify the base state. There will be no logic in this component but only render the buttons and take the functions as a prop. 

## Events Section
In this section, we will just render all the events that we will receive. There will be no logic in this component. It will just receive data and render the list accordingly. 

## Event Cards 
So with the new design, the cards will also be updated. 

# TODO
- [ ] Filter Section 
- [ ] Events Section
- [ ] New design for Event cards. - @kanishkaa24
- [ ] Events base Page 
   - [x] Retrieving data when the page loads. - @Souvikns 
   - [ ] Logic to update array of events according to the filter selected. 

---
> comment with the task of your choice to get assigned. 
> Also after you are assigned, create a new issue commenting this issue. as everyone discussing on this issue will get messy.  
---

**Comment by kanishkaa24** [comment]
I want to work with the new design for event cards.

**Comment by patel-atul** [comment]
Hey @Souvikns can I work on the code for new design.

**Comment by Souvikns** [comment]
@kanishkaa24 go ahead I am assigning you, create a separate issue for your work and start working.

**Comment by kanishkaa24** [comment]
Assign me please.

**Comment by kanishkaa24** [comment]
![EVENT Card](https://user-images.githubusercontent.com/71253790/103212000-b5f5af80-492f-11eb-952a-c7a2bdc67a6a.png)
![EVENT Card (1)](https://user-images.githubusercontent.com/71253790/103212003-b7bf7300-492f-11eb-84ca-f2c9001fe2a7.png)
I have designed these event cards.

**Comment by SuNiL-Chau** [comment]
> ![EVENT Card](https://user-images.githubusercontent.com/71253790/103212000-b5f5af80-492f-11eb-952a-c7a2bdc67a6a.png)
> ![EVENT Card (1)](https://user-images.githubusercontent.com/71253790/103212003-b7bf7300-492f-11eb-84ca-f2c9001fe2a7.png)
> I have designed these event cards.

Hey @kanishkaa24 the designing part is done the development phase is started kindly look for the design above.

**Comment by kanishkaa24** [comment]
> > ![EVENT Card](https://user-images.githubusercontent.com/71253790/103212000-b5f5af80-492f-11eb-952a-c7a2bdc67a6a.png)
> > ![EVENT Card (1)](https://user-images.githubusercontent.com/71253790/103212003-b7bf7300-492f-11eb-84ca-f2c9001fe2a7.png)
> > I have designed these event cards.
> 
> Hey @kanishkaa24 the designing part is done the development phase is started kindly look for the design above.

But in todo part, it's mentioned.

**Comment by SuNiL-Chau** [comment]
@kanishkaa24 it means to develop you got miss understood

**Comment by imabp** [comment]
I have deleted the unnecessary comments which can create confusion among the contributors.

@kanishkaa24  the design is up on the first comment by @Souvikns , 
It has been made by @SuNiL-Chau . 

We are planning to code it using react.

**Comment by kanishkaa24** [comment]
I misunderstood. I'm not looking for development based assignments.

**Comment by Souvikns** [comment]
@kanishkaa24 this is a development based assignment. The design has been decided now we need to convert it to a react component.

**Comment by Souvikns** [comment]
Ok, so I am gonna take up data loading work as right now it is occurring in the events component where the data is being rendered, but with the new design, we are gonna share that same data in two components, or rather two components will be sharing same data.
